// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	metrics "github.com/armon/go-metrics"
	mock "github.com/stretchr/testify/mock"
)

// MetricSink is an autogenerated mock type for the MetricSink type
type MetricSink struct {
	mock.Mock
}

// AddSample provides a mock function with given fields: key, val
func (_m *MetricSink) AddSample(key []string, val float32) {
	_m.Called(key, val)
}

// AddSampleWithLabels provides a mock function with given fields: key, val, labels
func (_m *MetricSink) AddSampleWithLabels(key []string, val float32, labels []metrics.Label) {
	_m.Called(key, val, labels)
}

// EmitKey provides a mock function with given fields: key, val
func (_m *MetricSink) EmitKey(key []string, val float32) {
	_m.Called(key, val)
}

// IncrCounter provides a mock function with given fields: key, val
func (_m *MetricSink) IncrCounter(key []string, val float32) {
	_m.Called(key, val)
}

// IncrCounterWithLabels provides a mock function with given fields: key, val, labels
func (_m *MetricSink) IncrCounterWithLabels(key []string, val float32, labels []metrics.Label) {
	_m.Called(key, val, labels)
}

// SetGauge provides a mock function with given fields: key, val
func (_m *MetricSink) SetGauge(key []string, val float32) {
	_m.Called(key, val)
}

// SetGaugeWithLabels provides a mock function with given fields: key, val, labels
func (_m *MetricSink) SetGaugeWithLabels(key []string, val float32, labels []metrics.Label) {
	_m.Called(key, val, labels)
}
